[toolchain]
anchor_version = "0.31.1"
solana_version = "2.1.21"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
airdrop = "HMsLRRqoo8SpnR9acz49Mq7ht19x93Kp62DdGFKoRTYe"

[programs.devnet]
airdrop = "HMsLRRqoo8SpnR9acz49Mq7ht19x93Kp62DdGFKoRTYe"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/dexter/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
